lesson_05/lesson_05/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
]

lesson_05/product/urls.py
from django.urls import path
from product.views import index, add

app_name = 'product'

urlpatterns = [
    path('', index, name='index'),
    path('add', add, name='add'),
]

lesson_05/product/models.py
from django.db import models


class Product(models.Model):
    UNITS = (
        (1, 'шт.'),
        (2, 'кг.'),
    )

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"

    name = models.CharField(verbose_name='название', max_length=128)
    date = models.DateField(verbose_name='дата поступления')
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=0, default=0)
    unit = models.IntegerField(verbose_name='единица измерения', choices=UNITS)
    provider = models.CharField(verbose_name='поставщик', max_length=256, blank=True)

lesson_05/product/forms.py
from django import forms
from product.models import Product


class DateInput(forms.DateInput):
    input_type = 'date'

class ProductForm(forms.ModelForm):
    class Meta:
        widgets = {'date': DateInput()}
        model = Product
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

lesson_05/product/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from product.forms import ProductForm
from product.models import Product


def index(request):
    return render(request, 'product/goods-list.html', {'products': Product.objects.all()})


def add(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'product/goods-list.html', {'products': Product.objects.all()})
        else:
            pass
    else:
        form = ProductForm()
    content = {'form': form}
    return render(request, 'product/good-create.html', content)

lesson_05/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block css %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    {% endblock %}

    {% block title %}
        <title>Shop</title>
    {% endblock %}

</head>
<body>
<div class="container">
    {% block header %}
        <div class="header">
            <h1><a href="/">Магазин "Плюс один"</a></h1>
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}

    <!-- окно добавления товара -->
    <div class="modal fade" id="modal-good">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <div class="modal-backdrop fade" style="display: none"></div>

</div>

{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/page.js' %}"></script>
{% endblock %}

</body>
</html>

lesson_05/templates/form.html
{% csrf_token %}
{{ form.as_p }}

lesson_05/templates/product/good-create.html
    <form
        method="post"
        enctype="multipart/form-data"
        data-action="{% url 'product:add' %}"
        class="form-horizontal js-good-create-form"
    >
        <div class="modal-body">
            {% include 'form.html' %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Create good</button>
        </div>
    </form>

lesson_05/templates/product/goods-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{#    <form action="{% url 'product:add' %}">#}
        <button
            class="js-create-good btn btn-primary"
            data-goods-url="{% url 'product:add' %}"
        >Добавить продукт</button>
{#    </form>#}

    <table class="table">
        <tr>
            <th>Название</th>
            <th>Цена</th>
            <th>Дата добавления</th>
            <th>Единица измерения</th>
            <th>Поставщик</th>
        </tr>
        {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.date }}</td>
                <td>{{ product.unit }}</td>
                <td>{{ product.provider }}</td>
            </tr>
        {% endfor %}
    </table>



{% endblock %}